vim.g.mapleader = " "

require("completion")
require("editing")
require("file-managers")
require("keymaps")
require("lsp")
require("markdown")
require("motions")
require("options")
require("search")
require("terminal")
require("treesitter")
require("ui")
require("version-control")
